### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by JanSawicki**
Updated README file
Extended and refreshed the description
Added infographics
Added expanding menus
Added authorship logos

### CODE REVIEW

**Comment by JanSawicki** [comment]
Please take into account that when you preview the README on the readme-update branch the images are not properly displayed, because they have relative paths to the master branch (destiny after merge).

**Comment by KarolAntczak** [comment]
@JanSawicki Ok. Could you push it then to master branch on your fork? I would like to see it.

**Comment by JanSawicki** [comment]
@KarolAntczak, Yes, you can examine it on https://github.com/JanSawicki/Dexter/tree/master.

**Comment by KarolAntczak** [comment]
Thanks. Looks really nice! 

image

One suggestion - ' Table of contents' should be unfolded by default.

**Comment by JanSawicki** [comment]
Of course, the "Table of contents" menu has been to changed to be opened by default with commit 0670410

**Pull request merged**
